<a href="https://colab.research.google.com/github/MichaelKupfer/MAT421/blob/main/mat421_hw5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Chapter 1 - Linear Equations

1.1 Linear Algebra and Systems of Linear Equations

Linear algebra can primarily be defined by vectors and matrices. Vectors can be either row or column vector and represent points in R^n. Vectors are linearly independent if none of the vectors can be written as a linear combination of the others. 

Matrices are tables of numbers and have several important properties such as determinant, rank, and inverse. One advantage of matrices is that they can be used to solve systems of linear equations. There are multiple methods to solve these systems such as: Gauss Elimination, Gauss-Jordan Elimination, LU Decomposition, and Gauss-Seidel. Of course, Python has its own function that uses LU Decomposition to solve these systems very quickly

Practice: Use solve method from numpy to find the solution to the system

In [1]:
import numpy as np

#A is the initial array and is a 3x3 matrix. Each row represents an equation while the columns represent the different variables.
A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
#y contains the right side values of the system of equations. 
y = np.array([2, 5, -3])

#use solve method to determine solutions
x = np.linalg.solve(A, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


This solution can be checked by also using the matrix inverse method which simply takes the inverse of the square and multiplies it with the y matrix.

Practice: Confirm solution using inverse

In [2]:
#Create the inverse matrix
A_inv = np.linalg.inv(A)

#Solve for x
x = np.dot(A_inv, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


We can also decompose the solution into the L and U matrices to follow along with the solution

In [3]:
from scipy.linalg import lu

P, L, U = lu(A)
print('P:\n', P)
print('L:\n', L)
print('U:\n', U)
print('LU:\n',np.dot(L, U))

P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
U:
 [[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]
LU:
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]


The P matrix is the permutation matrix that moves the equations around in order to create easier calculations. 

We can also use these methods to find inverses for larger and larger matrices. By setting the right side variables to be the corresponding values of [1,0,0,0] and solving the systems we can determine the inverse.

Practice: Find the inverse of a 4x4 matrix by using the solve method in numpy

In [24]:
#Create 4x4 matrix
M = np.array([[4, 3, -5, 1], 
              [-2, -4, 5, 3], 
              [8, 8, 0, 2],
              [4, 2, 3, 5]])

#Parameters for inverse
y1 = np.array([1,0,0,0])
y2 = np.array([0,1,0,0])
y3 = np.array([0,0,1,0])
y4 = np.array([0,0,0,1])

#Solve each system
x1 = np.linalg.solve(M, y1)
x2 = np.linalg.solve(M, y2)
x3 = np.linalg.solve(M, y3)
x4 = np.linalg.solve(M, y4)
print(x1)
print(x2)
print(x3)
print(x4)

#Confirm solution matches
M_inv = np.linalg.inv(M)
print(M_inv)

[ 0.72413793 -0.65517241 -0.06896552 -0.27586207]
[ 1.60344828 -1.37931034  0.27586207 -0.89655172]
[ 0.89655172 -0.62068966  0.22413793 -0.60344828]
[-1.46551724  1.20689655 -0.24137931  1.03448276]
[[ 0.72413793  1.60344828  0.89655172 -1.46551724]
 [-0.65517241 -1.37931034 -0.62068966  1.20689655]
 [-0.06896552  0.27586207  0.22413793 -0.24137931]
 [-0.27586207 -0.89655172 -0.60344828  1.03448276]]
